apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    apps: webapp
spec:
  containers:
    - name: webapp
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8081
# 将容器端口映射到宿主机         
