apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zrdapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zrdapp
      release: prod 
  template:
    metadata:
      name: zrdapp-pod
      labels: 
        app: zrdapp  # 必须和选择器匹配,否则无限创建资源
        release: prod 
    spec:
      containers:
      - name: zrdapp-container
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
