apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
    role: log-stor
  # type 默认是ClusterIp
  # ClusterIP 自动分配
  ports:
  - port: 6379 
    targetPort: 6379
    protocol: TCP

