apiVersion: v1
kind: Pod
metadata:
  name: mynode-affinity-demo
spec:
  containers:
  - name: mynode-affinity-demo
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In 
            values: ["ssd", "memory"]
          - key: env
            operator: In
            values:
            - test
            - prod
            
