apiVersion: v1
kind: Pod
metadata:
  name:  pod-affinityrequiredduring-scheduling-1
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: pod-affinity-required-during-scheduling-1
    image: ikubernetes/myapp:v1

---

apiVersion: v1
kind: Pod
metadata:
  name:  pod-affinity-required-during-scheduling-2
  labels:
    app: tomcat
    tier: db
spec:
  containers:
  - name: pod-affinity-required-during-scheduling-2
    image: ikubernetes/myapp:v1
  affinity: 
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - {"key": "app", "operator": "In", "values": ["myapp"] }
        topologyKey: kubernetes.io/hostname
