apiVersion: v1
kind: Pod
metadata:
  name: mypreferred-duringscheduling-ignored-during-execution
spec:
  containers:
  - name: mypreferred-duringscheduling-ignored-during-execution 
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: disktype
            operator: In 
            values: ["ssd", "memory"]
          - key: env
            operator: In
            values:
            - test
            - prod
        weight: 66     
