apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
    - name: nginx
      image: nginx:1.15
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80

