apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector: 
    app: myapp-pod
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp

spec:
  serviceName: myapp
  replicas: 3
  selector: 
    matchLabels:
      app: myapp-pod
  template:
    metadate:
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1

