apiVersion: v1
kind: Pod
metadata:
  name: host-vol-nfs
spec:
  containers:
  - name: host-vol-host-nfs
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    nfs:
      path: /nfs
      server: k8s-slave1-90
