apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo # pod 会引用
  namespace: default # pvc 有名称空间,而pv没有

spec:
  accessModes: 
  - ReadWriteOnce # 必须是pv的子集, pv有此属性, pvc才可以设置
  resources:  # pv 必大于等于才可以省钱
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-test
  namespace: default
spec:
  containers:
  - name: nginx-pvc-test
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html  # 从volumes列表name中获取
      
  volumes:
  - name: html  # 会被引用
    persistentVolumeClaim: 
      claimName: pvc-demo  # 从pvc设置  metadata.name  中获取
      readOnly: false
  
