apiVersion: v1
kind: Pod
metadata:
  name: cm-from-pod-medata
spec:
  containers:
  - name: cm-from-pod-medata
    image: busybox
    command: ['sh', '-c', 'sleep 60']
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NS
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

