apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
  - name: cm-test
    image: busybox
    command: ['sh' , '-c', "sleep 9000"]
    env:
    - name: NGINXPORT
      valueFrom:
        configMapKeyRef:
          name: my-nginxport 
          key: nginxport



#  kubectl create configmap my-nginxport --from-literal=nginxport=80 --from-literal=nginxdatadir=/var/www  
