apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp-socket
  labels:
    test: liveness-tcp-socket
spec:
  containers:
    - name: liveness-tcp-socket
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 30 #  容器启动后,首次检查等待时间
        timeoutSeconds: 1

# 以tcp socket 方式检查容器健康
