apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # 参照pod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx
