apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    name: volume-pod
spec:
  volumes:
  - name: app-logs
    emptyDir: {} 

  containers:
  - name: tomcat
    image: tomcat
    ports:
    - name: app-log
      containerPort: 8080
    volumeMounts:
      - name: app-logs
        mountPath: /usr/local/tomcat/logs
  - name: busybox
    image: busybox
    command: ['sh', '-c','sleep 3600']
    volumeMounts:
    - name: app-logs
      mountPath: /logs
